dist: xenial
language: generic

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make docker-multiarch
deploy:
  provider: script
  script: make docker-push
  on:
    tags: true