#!/bin/bash

export TAG=`echo $DOCKER_TAG | cut -d- -f1`
export ARCH=`echo $DOCKER_TAG | cut -d- -f2`

docker manifest create -a "$DOCKER_REPO:$TAG" "$IMAGE_NAME"

case $ARCH in
  amd64)
    docker manifest annotate "$DOCKER_REPO:$TAG" "$IMAGE_NAME" --os linux --arch $ARCH
    ;;
  arm64)
    docker manifest annotate "$DOCKER_REPO:$TAG" "$IMAGE_NAME" --os linux --arch $ARCH --variant v8
    ;;
  arm32)
    docker manifest annotate "$DOCKER_REPO:$TAG" "$IMAGE_NAME" --os linux --arch arm --variant v7
    ;;
esac

docker manifest push "$DOCKER_REPO:$TAG"
