#!/bin/bash

export DOCKER_CLI_EXPERIMENTAL=enabled
export TAG=`echo $DOCKER_TAG | cut -d- -f1`

docker pull "$IMAGE_NAME":"$TAG"-arm64 || exit 0
docker pull "$IMAGE_NAME":"$TAG"-amd64 || exit 0
docker pull "$IMAGE_NAME":"$TAG"-arm32 || exit 0

docker manifest create "$IMAGE_NAME":"$TAG"-arm34

docker manifest rm "$IMAGE_NAME:$TAG" || true
docker manifest create "$IMAGE_NAME:$TAG" "$IMAGE_NAME":"$TAG"-amd64
docker manifest create -a "$IMAGE_NAME:$TAG" "$IMAGE_NAME":"$TAG"-arm64
docker manifest create -a "$IMAGE_NAME:$TAG" "$IMAGE_NAME":"$TAG"-arm32

docker manifest push "$IMAGE_NAME:$TAG"
