---
name: Auto Actions

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
    - main
  pull_request_target:
    types: [labeled, unlabeled, synchronize, review_requested, opened, reopened]

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot-automerge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
    - name: Gather Dependabot metadata
      id: metadata
      uses: dependabot/fetch-metadata@v1.1.1
      with:
        github-token: ${{ secrets.AUTO_MERGE_TOKEN }}
    - name: Approve PR
      run: gh pr review --approve "$PR_URL"
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GITHUB_TOKEN: ${{secrets.AUTO_MERGE_TOKEN}}
    - name: Enable auto-merge
      run: gh pr merge --auto --squash "$PR_URL"
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GITHUB_TOKEN: ${{secrets.AUTO_MERGE_TOKEN}}
