---
name: Refresh the latest docker tag

on:  # yamllint disable-line rule:truthy
  schedule:
  - cron: 0 8 * * *

jobs:
  release:
    name:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        image: tonistiigi/binfmt:latest
        platforms: all
    - name: Setup buildx
      uses: docker/setup-buildx-action@v1
    - name: Docker meta
      id: meta
      uses: crazy-max/ghaction-docker-meta@v3
      with:
        images: kong/fpm
        tags: |
          type=ref,event=branch
    - name: Build Only
      uses: docker/bake-action@v1
      with:
        files: |
          ./docker-bake.hcl
          ${{ steps.meta.outputs.bake-file }}
        targets: build
    - name: Build & Push
      uses: docker/bake-action@v1
      with:
        push: 'true'
        files: |
          ./docker-bake.hcl
          ${{ steps.meta.outputs.bake-file }}
        targets: build
